	var routes="Routes";
	var config="Configuration";
	var fitxaLabel="Data Sheet";
	var map="Map";
	var medals="Medals";
	var curses="Races";
	var idioma ="Language";
	var selected = "You have selected: ";
	if (Ti.Platform.name === 'iPhone OS'){	
		var canvi_idioma= "You must restart the App for the language to change";
	}else{
		var canvi_idioma ="You must restart the App for the language to change";
	}
	var cancelButton = "Cancel";

	var lowAccuracy="You can't start a route if your GPS signal is low or null, you should go to a wider place.";
	var nogps="Location is not enabled, you have to enable it.";

	var finishButtonText="Have you finished the route?";
	var yes="Yes";
	var no="No";
	var resetButtonText="Do you really want to reset the route?";
	var pause2back="You need to stop the timer to exit the route.";
	
	
    var loading = "Loading"
    var unknown = "Temporaly not available"
    var table_path = "/images/air_quality_en.png"
    var pollen_msg = "The pollen and weather data are general for all Barcelona"
    var pollution_update_TS = "Pollution data have been updated for last time at: "
    
   var temperature = "Temperature"
   var temperature_max = "Temp. max"
   var temperature_min = "Temp. min"
    


	var nomCursa = [];

	var nomCursa1="santantoni";
	nomCursa.push(nomCursa1);
	var nomCursa2="halfmarathon";
	nomCursa.push(nomCursa2);
	var nomCursa3="marathon";
	nomCursa.push(nomCursa3);
	var nomCursa4="firemans";
	nomCursa.push(nomCursa4);
	var nomCursa5="Elcorteingles";
	nomCursa.push(nomCursa5);
	var nomCursa6="lamerce";
	nomCursa.push(nomCursa6);
	var nomCursa7="friendship";
	nomCursa.push(nomCursa7);
	var nomCursa8="womens";
	nomCursa.push(nomCursa8);
	var nomCursa9="JeanBouin";
	nomCursa.push(nomCursa9);
	var nomCursa10="nassos";
	nomCursa.push(nomCursa10);

	var moreInfo="More information: ";
	var date="Date: ";

	var meters=" meters";

	var data = [];

	var data0="January";
	data.push(data0);
	var data1="February";
	data.push(data1);
	var data2="March";
	data.push(data2);
	var data3="April";
	data.push(data3);
	var data4="May";
	data.push(data4);
	var data5="September";
	data.push(data5);
	var data6="November";
	data.push(data6);
	var data7="November";
	data.push(data7);
	var data8="November";
	data.push(data8);
	var data9="December";
	data.push(data9);

	var mapData = [];

	var mapData0="2013 Track";
	mapData.push(mapData0);
	var mapData1="2012 Track";
	mapData.push(mapData1);
	var mapData2="2013 Track";
	mapData.push(mapData2);
	var mapData3="2012 Track";
	mapData.push(mapData3);
	var mapData4="2012 Track";
	mapData.push(mapData4);
	var mapData5="2012 Track";
	mapData.push(mapData5);
	var mapData6="2012 Track";
	mapData.push(mapData6);
	var mapData7="2012 Track";
	mapData.push(mapData7);
	var mapData8="2012 Track";
	mapData.push(mapData8);
	var mapData9="2012 Track";
	mapData.push(mapData9);

	var alert100m="Stop the timer and go back one screen to activate the clock correctly at the start of the route. You are at ";
	var alert100m2="m from the beginning. To win the medal of the route, the start point and end point must be valid.";

	var links = [];

	var link0="http://www.cursasantantoni.cat/";
	links.push(link0);
	var link1="http://www.mitjabarcelona.com/";
	links.push(link1);
	var link2="http://www.zurichmaratobarcelona.es/";
	links.push(link2);
	var link3="http://www.cursabombers.com/";
	links.push(link3);
	var link4="http://www.cursaelcorteingles.cat/";
	links.push(link4);
	var link5="http://www.bcn.cat/cursamerce/";
	links.push(link5);
	var link6="http://www.cursadelamistat.com/";
	links.push(link6);
	var link7="http://www.carreradelamujer.com/barcelona/";
	links.push(link7);
	var link8="http://jeanbouin.mundodeportivo.com/";
	links.push(link8);
	var link9="http://www.bcn.cat/cursanassos/";
	links.push(link9);

	var alert100mts="alert100m";



	var wrongText="Incorrect data. Please, check it.";
	var info="With this data we can give you an approximation of ran distance, speed and burnt calories:";
	var save="Save";
	var reset="Reset";
	var age="Age:";
	var height="Height (cm):";
	var weight="Weight (Kg):";

	var based="Aplication based on the book: ";
	var idea="Original Idea: ";
	var autor="Authors: ";
	var fotograf="Photo:";
	var dev="Development:";
	var done="Done";
	var next="Next";


	var arrayCursatext=[];

	var cursatext0="This is the first big event of the season. If the excesses of Christmas are weighing on you, this is the perfect excuse to begin training in January. Starting next to the market, it goes twice round the neighbourhood, including two long stretches on Gran Via de les Corts Catalanes in the direction of the Besòs. The race has made a name for itself on its own merits and leading Catalan professional athletes usually take part. On the day of the race, there are also races for children of five and up. The main difficulty of the race is the cold at the beginning. Warming up is more necessary than ever and you may have to run in long sleeves to keep your muscles at the right temperature. Every year there’s a long list of entrants, because this is probably the hardest middle-distance race on the local calendar.";
	arrayCursatext.push(cursatext0);
	var cursatext1="This is the little sister of the big race and the next step in preparing for the great event, which is held a few weeks later. For most runners it provides a first-rate training opportunity as part of their programme. The organisers have the support of the French company Amaury Sport Organisation, which is also behind mythical competitions like the Tour de France and the Dakar Rally. This helps attract Kenyan stars, who dominate the distance. The weather can be troublesome, with rain, but the temperature is usually mild. The course always runs near the seafront and takes in a lot of the city’s emblematic tourist sites.";
	arrayCursatext.push(cursatext1);
	var cursatext2="In 1980 Barcelona joined the list of big cities with their own marathon. It did so by attracting the one that had been organised for the first time two years earlier in Palafrugell. At that first edition, which started from Plaça de Maria Cristina and went round Baix Llobregat, barely 1,000 people enrolled. Since the mid-1990s, the race fully succumbed to the Olympic fever gripping the city. The introduction of the yellow chip in 1995 is still remembered today as the definitive turning point.In recent years the race has become a world reference. The 4,636 participants in 2006 grew to 15,075 in 2011. the course is quite fast, in spite of the slopes of Diagonal and Passeig de Sant Joan, where you can see the odd grimace of pain. The weather is usually favourable, which means that each year there are more foreign participants, who take advantage of the race to visit the city. The route has been much improved in recent years, which for them is the first sample of the attractions the city has to offer.";
	arrayCursatext.push(cursatext2);
	var cursatext3="This is definitely one of the phenomena that has grown parallel to the surge in running in the city. It started as a partnership between Nike and the Barcelona Fire Brigade, with a marketing campaign which over the years has made it one of the challenges not to be missed on the local calendar. At the last edition, the 20,000 places available were taken up within a week. The river of yellow sweatshirts is now a spring classic. In the weeks before the race, the organisers get the entrants together for supervised training sessions, some of them with the presence of top-level athletes. There are also popular night-time sessions, known as the Lunarun. As far as competing goes, the course is extremely fast. Track athletes such as Natalia Rodríguez, Marta Domínguez or Chema Martínez are regulars at this event. In fact, this is the only race in Catalonia to bear the distinction of the Bronze Label of the International Athletics Federation, a label that guarantees quality.";
	arrayCursatext.push(cursatext3);
	var cursatext4="The queen of Barcelona races, at least as regards inscriptions. The fact that it’s free has something to do with it, but there’s more to it than that. The Corte Inglés race, thanks to the brand sponsoring it, has become a real institution in its own right. Even in the first edition it drew more than 17,000 runners. Since then it hasn’t stopped growing. The course isn’t a standard length, but it always fulfils one of its own traditions: the ascent to Montjuïc up Carrer del Foc and the return via the Lluís Companys Olympic Stadium. Your legs will feel the 119 metres of the cumulative ascent, but a lot of people taking part think nothing of slowing down or even walking at some point along the way. This event went down in history in 1994, when 109,457 athletes turned out and established a Guinness world record for a race, which is still standing today. Participation has currently settled around 50,000 to 60,000, a figure that makes it the most popular in the city.";
	arrayCursatext.push(cursatext4);
	var cursatext5="The city’s main annual feast day could hardly go by without an athletics meeting. On the occasion of La Mercè, the City Council organises this race on a Sunday morning as the starting signal for the festivities. The course is a 10-kilometre classic with a very demanding stretch near the beginning, with 3,000 metres along Gran Via de les Corts Catalanes. For a lot of people, this is the first race after the holidays. The heat has eased up by now, which encourages a lot of people. All the available places are often taken up, Enrolment costs five euros and the takings go to pay for projects to help handicapped people through sport. The sporting level is high, because the circuit is designed to achieve fast times. In spite of that, it doesn’t go after big international names so as to preserve the traditional festive air of the event.";
	arrayCursatext.push(cursatext5);
	var cursatext6="At the beginning of the 1980s, when Barcelona still didn’t have a complete athletics calendar, Francesc Mates decided to organise a race which still stands out above the rest today. He did away with a gap that he felt needed to be filled: a mountain race without leaving the city. Francesc at that time was a key figure in urban athletics in Barcelona. Since 1947 he had been designing sports shoes for runners. He was also one of the driving forces behind the Barcelona Marathon, along with Ramon Oliu. This was how the Friendship Race began life. Every year since 1991 this non-competitive event has commemorated its creator. It’s a modest race, as it’s still organised by the Mates family through their shoe- making business. Francesc’s daughter Myrna Mates, a skilled shoe-maker and, like her father, an ex-athlete, is now the firm’s visible face. Amongst the sports community the race is known quite simply as the ‘Mates family race’. Being a friendly race, it’s not run with a chip and exact times aren’t measured. In fact, the final classification is always unofficial. Enrolment is free.";
	arrayCursatext.push(cursatext6);
	var cursatext7="In the last few years, the growth in participation by women has accounted for a large part of the exponential increase in inscriptions in all the races contested in the city. Between 20 and 25% of people taking part are women. But one Sunday in October they are the ones in charge in the street. This race is also part of the national circuit, but it also has links to Woman’s Sports Week, seven days during which admission to municipal facilities and sports classes is free. Inscription for the race is by payment, but part of it goes to the Spanish Cancer Association. This pledge means there is no lack of well-known faces, like María Vasco or Érika Villaécija. There is a predominantly festive atmosphere. The event has been an undisputed success with the women of Barcelona and in five years inscriptions have multiplied by five. For a lot of the women, this is an initial race that hooks them for others.";
	arrayCursatext.push(cursatext7);
	var cursatext8="No matter how many races there are on the local calendar, none is as old- established as the Jean Bouin. On 1 February 1920, 48 pioneers lined up at the start of the first edition, in Esplugues de Llobregat. The winner that day was Rossend Calvet, with an excellent time of 34’ 10”. Nine decades later, the Jean Bouin is the grand old man of Spanish athletics races, with an almost unbroken history. The race is held in memory of an athlete from Marseille who died in 1914 on a First World War battlefield. Two years earlier, he had won the silver medal for the 5,000 metres at the Stockholm Olympics, earning himself a host of followers. At the first editions the public was already behind the brave runners and poured into the street to cheer them on. With this backing, the Jean Bouin went on to new breakthroughs, in 1946 it was opened up to foreign athletes and the following year to women. In 1987 it added a category for wheelchairs and in 2005 for transplant patients. In 1979 the race was definitively extended to citizens when it was made open to everybody. At the beginning of the 21st century, participation figures brushed the 1,000 mark, but within a few years it had made an enormous leap. The present circuit, which is almost identical to the 1973 circuit, begins with a long stretch along Gran Via de les Corts Catalanes and ends with a steep, 50-metre climb on Montjuïc. The morning chill of autumn complicates the experience, but don’t hesitate to take part in an incomparable story.";
	arrayCursatext.push(cursatext8);
	var cursatext9="Between your Christmas dinner and New Year’s Eve toasts, the last afternoon of December offers an opportunity to see the year out burning calories. The Saint Sylvester tradition began in 1925 in São Paulo, where the weather at this time of year lends itself to running more than it does here. In Barcelona it has taken the name L’Home dels Nassos (‘The man with the noses’), a character with ‘as many noses as the day has years’, who children are told to look for on the last day of the year. The course is extremely fast and runs along the coast with hardly any slopes. This race has seen such impressive times as the Spanish record set by the athlete Rosa Morató from Navarcles. The race ends after sundown, which is unusual in amateur competitions, but participation nevertheless goes up year after year. The route makes for a festive atmosphere as an appetiser for New Year’s Eve dinner, where you can tell everyone all about your race.";
	arrayCursatext.push(cursatext9);

	var free="Free";

	var correct="Correct";
	var incorrect="Incorrect";

	var initPointText="Start Point:";
	var finalPointText="End Point:";
	var timeLabelText="Time:";
	var distanceLabelText="Distance:";
	var velocityLabelText="Average pace:";
	var calorieLabelText="Energy:";
	var medalLabelText="Achieved Medals:";

	var distance="Distance:";
	var sign="Signposting:";
	var terrain="Surface:";
	var day="Day/Night:";
	var desP="Net ascent:";
	var desA="Total cumulative ascent:";
	var espV="Green zones:";
	var water="Drinking fountains:";
	var time="Time:";
	var dif="Difficulty:";
	
    var pollution="Pollution";
    var pollen = "Pollen";
    var weather_title = "Weather"

	var arrayMedalBarTitle = [];
	var arrayMedalBarColor = [];

	var medalBarTitle1="BCN Corre Routes";
	var medalBarColor1="white";
	arrayMedalBarTitle.push(medalBarTitle1);
	arrayMedalBarColor.push(medalBarColor1);
	arrayMedalBarTitle.push(medalBarTitle1);
	arrayMedalBarColor.push(medalBarColor1);

	var medalBarTitle2="BCN Corre Races";
	var medalBarColor2="#F8B905";
	arrayMedalBarTitle.push(medalBarTitle2);
	arrayMedalBarColor.push(medalBarColor2);

	var medalBarTitle3="Distance";
	var medalBarColor3="#00A096";
	arrayMedalBarTitle.push(medalBarTitle3);
	arrayMedalBarColor.push(medalBarColor3);

	var medalBarTitle4="Speed";
	var medalBarColor4="#DF2477";
	arrayMedalBarTitle.push(medalBarTitle4);
	arrayMedalBarColor.push(medalBarColor4);

	var medalBarTitle5="Calories";
	var medalBarColor5="#E75F15";
	arrayMedalBarTitle.push(medalBarTitle5);
	arrayMedalBarColor.push(medalBarColor5);

	var medalBarTitle6="Number of routes completed this month";
	var medalBarColor6="#93107D";
	arrayMedalBarTitle.push(medalBarTitle6);
	arrayMedalBarColor.push(medalBarColor6);



	var arrayDistance = [];
	var arraySign = [];
	var arrayTerrain = [];
	var arrayDay = [];
	var arrayDesP = [];
	var arrayDesA = [];
	var arrayEspV = [];
	var arrayWater = [];
	var arrayTime = [];
	var arrayDif = [];
	var arrayDif_image = [];

	var arrayDistance1="4800 METRES";
	var arraySign1="Montjuïc Castle sports circuit";
	var arrayTerrain1="ASPHALT AND GRAVEL";
	var arrayDay1="DAY";
	var arrayDesP1="149 METRES";
	var arrayDesA1="168 METRES";
	var arrayEspV1="images/niveles/nivelbosque3.png";
	var arrayWater1="images/niveles/nivelfuentes1.png";
	var arrayTime1="50 MINUTES";
	var arrayDif1="HIGH";
	var arrayDif_image1="images/niveles/niveldificultad8.png";

	arrayDistance.push(arrayDistance1);
	arraySign.push(arraySign1);
	arrayTerrain.push(arrayTerrain1);
	arrayDay.push(arrayDay1);
	arrayDesP.push(arrayDesP1);
	arrayDesA.push(arrayDesA1);
	arrayEspV.push(arrayEspV1);
	arrayWater.push(arrayWater1);
	arrayTime.push(arrayTime1);
	arrayDif.push(arrayDif1);
	arrayDif_image.push(arrayDif_image1);
	arrayDistance.push(arrayDistance1);
	arraySign.push(arraySign1);
	arrayTerrain.push(arrayTerrain1);
	arrayDay.push(arrayDay1);
	arrayDesP.push(arrayDesP1);
	arrayDesA.push(arrayDesA1);
	arrayEspV.push(arrayEspV1);
	arrayWater.push(arrayWater1);
	arrayTime.push(arrayTime1);
	arrayDif.push(arrayDif1);
	arrayDif_image.push(arrayDif_image1);

	var arrayDistance2="6000 METRES";
	var arraySign2="NO";
	var arrayTerrain2="ASPHALT AND GRAVEL";
	var arrayDay2="MORNING AND AFTERNOON";
	var arrayDesP2="0 METRES";
	var arrayDesA2="22 METRES";
	var arrayEspV2="images/niveles/nivelbosque1.png";
	var arrayWater2="images/niveles/nivelfuentes1.png";
	var arrayTime2="40 MINUTES";
	var arrayDif2="MEDIUM";
	var arrayDif_image2="images/niveles/niveldificultad5.png";
	arrayDistance.push(arrayDistance2);
	arraySign.push(arraySign2);
	arrayTerrain.push(arrayTerrain2);
	arrayDay.push(arrayDay2);
	arrayDesP.push(arrayDesP2);
	arrayDesA.push(arrayDesA2);
	arrayEspV.push(arrayEspV2);
	arrayWater.push(arrayWater2);
	arrayTime.push(arrayTime2);
	arrayDif.push(arrayDif2);
	arrayDif_image.push(arrayDif_image2);

	var arrayDistance3="6000 METRES";
	var arraySign3="Av. Diagonal sports circuit";
	var arrayTerrain3="ASPHALT AND GRAVEL";
	var arrayDay3="MORNING AND AFTERNOON";
	var arrayDesP3="0 METRES";
	var arrayDesA3="89 METRES";
	var arrayEspV3="images/niveles/nivelbosque2.png";
	var arrayWater3="images/niveles/nivelfuentes1.png";
	var arrayTime3="45 MINUTES";
	var arrayDif3="MEDIUM-LOW";
	var arrayDif_image3="images/niveles/niveldificultad4.png";
	arrayDistance.push(arrayDistance3);
	arraySign.push(arraySign3);
	arrayTerrain.push(arrayTerrain3);
	arrayDay.push(arrayDay3);
	arrayDesP.push(arrayDesP3);
	arrayDesA.push(arrayDesA3);
	arrayEspV.push(arrayEspV3);
	arrayWater.push(arrayWater3);
	arrayTime.push(arrayTime3);
	arrayDif.push(arrayDif3);
	arrayDif_image.push(arrayDif_image3);

	var arrayDistance4="6000 METRES";
	var arraySign4="NO";
	var arrayTerrain4="ASPHALT AND GRAVEL";
	var arrayDay4="MORNING AND AFTERNOON";
	var arrayDesP4="0 METRES";
	var arrayDesA4="89 METRES";
	var arrayEspV4="images/niveles/nivelbosque2.png";
	var arrayWater4="images/niveles/nivelfuentes2.png";
	var arrayTime4="50 MINUTES";
	var arrayDif4="LOW-MEDIUM";
	var arrayDif_image4="images/niveles/niveldificultad4.png";
	arrayDistance.push(arrayDistance4);
	arraySign.push(arraySign4);
	arrayTerrain.push(arrayTerrain4);
	arrayDay.push(arrayDay4);
	arrayDesP.push(arrayDesP4);
	arrayDesA.push(arrayDesA4);
	arrayEspV.push(arrayEspV4);
	arrayWater.push(arrayWater4);
	arrayTime.push(arrayTime4);
	arrayDif.push(arrayDif4);
	arrayDif_image.push(arrayDif_image4);

	var arrayDistance5="4800 METRES";
	var arraySign5="Sports circuits of Rambla de Prim and Diagonal-Sant Martí";
	var arrayTerrain5="ASPHALT";
	var arrayDay5="24 HOURS";
	var arrayDesP5="0 METRES";
	var arrayDesA5="6,3 METRES";
	var arrayEspV5="images/niveles/nivelbosque2.png";
	var arrayWater5="images/niveles/nivelfuentes1.png";
	var arrayTime5="30 MINUTES";
	var arrayDif5="LOW";
	var arrayDif_image5="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance5);
	arraySign.push(arraySign5);
	arrayTerrain.push(arrayTerrain5);
	arrayDay.push(arrayDay5);
	arrayDesP.push(arrayDesP5);
	arrayDesA.push(arrayDesA5);
	arrayEspV.push(arrayEspV5);
	arrayWater.push(arrayWater5);
	arrayTime.push(arrayTime5);
	arrayDif.push(arrayDif5);
	arrayDif_image.push(arrayDif_image5);

	var arrayDistance6="5300 METRES";
	var arraySign6="NO";
	var arrayTerrain6="ASPHALT, GRAVEL AND GRASS";
	var arrayDay6="DAY";
	var arrayDesP6="95 METRES";
	var arrayDesA6="157 METRES";
	var arrayEspV6="images/niveles/nivelbosque3.png";
	var arrayWater6="images/niveles/nivelfuentes2.png";
	var arrayTime6="45 MINUTES";
	var arrayDif6="MEDIUM";
	var arrayDif_image6="images/niveles/niveldificultad5.png";
	arrayDistance.push(arrayDistance6);
	arraySign.push(arraySign6);
	arrayTerrain.push(arrayTerrain6);
	arrayDay.push(arrayDay6);
	arrayDesP.push(arrayDesP6);
	arrayDesA.push(arrayDesA6);
	arrayEspV.push(arrayEspV6);
	arrayWater.push(arrayWater6);
	arrayTime.push(arrayTime6);
	arrayDif.push(arrayDif6);
	arrayDif_image.push(arrayDif_image6);

	var arrayDistance7="5200 METRES";
	var arraySign7="NO";
	var arrayTerrain7="ASPHALT AND GRAVEL";
	var arrayDay7="MORNING AND AFTERNOON";
	var arrayDesP7="99.7 METRES";
	var arrayDesA7="137 METRES";
	var arrayEspV7="images/niveles/nivelbosque3.png";
	var arrayWater7="images/niveles/nivelfuentes3.png";
	var arrayTime7="50 MINUTES";
	var arrayDif7="HIGH";
	var arrayDif_image7="images/niveles/niveldificultad8.png";
	arrayDistance.push(arrayDistance7);
	arraySign.push(arraySign7);
	arrayTerrain.push(arrayTerrain7);
	arrayDay.push(arrayDay7);
	arrayDesP.push(arrayDesP7);
	arrayDesA.push(arrayDesA7);
	arrayEspV.push(arrayEspV7);
	arrayWater.push(arrayWater7);
	arrayTime.push(arrayTime7);
	arrayDif.push(arrayDif7);
	arrayDif_image.push(arrayDif_image7);

	var arrayDistance8="5800 METRES";
	var arraySign8="NO";
	var arrayTerrain8="ASPHALT, GRAVEL, PAVING AND GRASS";
	var arrayDay8="24 HOURS";
	var arrayDesP8="68.5 METRES";
	var arrayDesA8="96.7 METRES";
	var arrayEspV8="images/niveles/nivelbosque2.png";
	var arrayWater8="images/niveles/nivelfuentes1.png";
	var arrayTime8="50 MINUTES";
	var arrayDif8="HIGH";
	var arrayDif_image8="images/niveles/niveldificultad8.png";
	arrayDistance.push(arrayDistance8);
	arraySign.push(arraySign8);
	arrayTerrain.push(arrayTerrain8);
	arrayDay.push(arrayDay8);
	arrayDesP.push(arrayDesP8);
	arrayDesA.push(arrayDesA8);
	arrayEspV.push(arrayEspV8);
	arrayWater.push(arrayWater8);
	arrayTime.push(arrayTime8);
	arrayDif.push(arrayDif8);
	arrayDif_image.push(arrayDif_image8);

	var arrayDistance9="7000 METRES";
	var arraySign9="NO";
	var arrayTerrain9="ASPHALT";
	var arrayDay9="MORNING AND AFTERNOON";
	var arrayDesP9="0 METRES";
	var arrayDesA9="164 METRES";
	var arrayEspV9="images/niveles/nivelbosque2.png";
	var arrayWater9="images/niveles/nivelfuentes2.png";
	var arrayTime9="60 MINUTES";
	var arrayDif9="MEDIUM-HIGH";
	var arrayDif_image9="images/niveles/niveldificultad7.png";
	arrayDistance.push(arrayDistance9);
	arraySign.push(arraySign9);
	arrayTerrain.push(arrayTerrain9);
	arrayDay.push(arrayDay9);
	arrayDesP.push(arrayDesP9);
	arrayDesA.push(arrayDesA9);
	arrayEspV.push(arrayEspV9);
	arrayWater.push(arrayWater9);
	arrayTime.push(arrayTime9);
	arrayDif.push(arrayDif9);
	arrayDif_image.push(arrayDif_image9);

	var arrayDistance10="6300 METRES";
	var arraySign10="NO";
	var arrayTerrain10="ASPHALT, GRAVEL AND GRASS";
	var arrayDay10="MORNING AND AFTERNOON";
	var arrayDesP10="141 METRES";
	var arrayDesA10="301 METRES";
	var arrayEspV10="images/niveles/nivelbosque4.png";
	var arrayWater10="images/niveles/nivelfuentes2.png";
	var arrayTime10="60 MINUTES";
	var arrayDif10="HIGH";
	var arrayDif_image10="images/niveles/niveldificultad8.png";
	arrayDistance.push(arrayDistance10);
	arraySign.push(arraySign10);
	arrayTerrain.push(arrayTerrain10);
	arrayDay.push(arrayDay10);
	arrayDesP.push(arrayDesP10);
	arrayDesA.push(arrayDesA10);
	arrayEspV.push(arrayEspV10);
	arrayWater.push(arrayWater10);
	arrayTime.push(arrayTime10);
	arrayDif.push(arrayDif10);
	arrayDif_image.push(arrayDif_image10);

	var arrayDistance11="7000 METRES";
	var arraySign11="Sports circuit of the Parc de la Ciutadella";
	var arrayTerrain11="ASPHALT, GRAVEL AND GRASS";
	var arrayDay11="10 AM - NIGHTFALL";
	var arrayDesP11="2.1 METRES";
	var arrayDesA11="0 METRES";
	var arrayEspV11="images/niveles/nivelbosque3.png";
	var arrayWater11="images/niveles/nivelfuentes2.png";
	var arrayTime11="40 MINUTES";
	var arrayDif11="LOW";
	var arrayDif_image11="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance11);
	arraySign.push(arraySign11);
	arrayTerrain.push(arrayTerrain11);
	arrayDay.push(arrayDay11);
	arrayDesP.push(arrayDesP11);
	arrayDesA.push(arrayDesA11);
	arrayEspV.push(arrayEspV11);
	arrayWater.push(arrayWater11);
	arrayTime.push(arrayTime11);
	arrayDif.push(arrayDif11);
	arrayDif_image.push(arrayDif_image11);

	var arrayDistance12="5200 METRES";
	var arraySign12="Passeig Marítim sports circuit";
	var arrayTerrain12="ASPHALT, GRAVEL AND GRASS";
	var arrayDay12="DAY AND NIGHT";
	var arrayDesP12="0 METRES";
	var arrayDesA12="8 METRES";
	var arrayEspV12="images/niveles/nivelbosque3.png";
	var arrayWater12="images/niveles/nivelfuentes4.png";
	var arrayTime12="30 MINUTES";
	var arrayDif12="LOW";
	var arrayDif_image12="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance12);
	arraySign.push(arraySign12);
	arrayTerrain.push(arrayTerrain12);
	arrayDay.push(arrayDay12);
	arrayDesP.push(arrayDesP12);
	arrayDesA.push(arrayDesA12);
	arrayEspV.push(arrayEspV12);
	arrayWater.push(arrayWater12);
	arrayTime.push(arrayTime12);
	arrayDif.push(arrayDif12);
	arrayDif_image.push(arrayDif_image12);

	var arrayDistance13="5300 METRES";
	var arraySign13="NO";
	var arrayTerrain13="ASPHALT AND GRAVEL";
	var arrayDay13="10 PM - NIGHTFALL";
	var arrayDesP13="-23.4 METRES";
	var arrayDesA13="13 METRES";
	var arrayEspV13="images/niveles/nivelbosque2.png";
	var arrayWater13="images/niveles/nivelfuentes4.png";
	var arrayTime13="60 MINUTES";
	var arrayDif13="MEDIUM-LOW";
	var arrayDif_image13="images/niveles/niveldificultad3.png";
	arrayDistance.push(arrayDistance13);
	arraySign.push(arraySign13);
	arrayTerrain.push(arrayTerrain13);
	arrayDay.push(arrayDay13);
	arrayDesP.push(arrayDesP13);
	arrayDesA.push(arrayDesA13);
	arrayEspV.push(arrayEspV13);
	arrayWater.push(arrayWater13);
	arrayTime.push(arrayTime13);
	arrayDif.push(arrayDif13);
	arrayDif_image.push(arrayDif_image13);

	var arrayDistance14="4100 METRES";
	var arraySign14="NO";
	var arrayTerrain14="ASPHALT";
	var arrayDay14="MORNINGS (very early)";
	var arrayDesP14="0 METRES";
	var arrayDesA14="22 METRES";
	var arrayEspV14="images/niveles/nivelbosque1.png";
	var arrayWater14="images/niveles/nivelfuentes2.png";
	var arrayTime14="30 MINUTES";
	var arrayDif14="LOW";
	var arrayDif_image14="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance14);
	arraySign.push(arraySign14);
	arrayTerrain.push(arrayTerrain14);
	arrayDay.push(arrayDay14);
	arrayDesP.push(arrayDesP14);
	arrayDesA.push(arrayDesA14);
	arrayEspV.push(arrayEspV14);
	arrayWater.push(arrayWater14);
	arrayTime.push(arrayTime14);
	arrayDif.push(arrayDif14);
	arrayDif_image.push(arrayDif_image14);

	var arrayDistance15="6000 METRES";
	var arraySign15="Can Dragó sports circuit";
	var arrayTerrain15="ASPHALT AND SAND";
	var arrayDay15="MORNINGS AND AFTERNOONS";
	var arrayDesP15="-40 METRES";
	var arrayDesA15="4 METRES";
	var arrayEspV15="images/niveles/nivelbosque2.png";
	var arrayWater15="images/niveles/nivelfuentes2.png";
	var arrayTime15="20 MINUTES";
	var arrayDif15="LOW";
	var arrayDif_image15="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance15);
	arraySign.push(arraySign15);
	arrayTerrain.push(arrayTerrain15);
	arrayDay.push(arrayDay15);
	arrayDesP.push(arrayDesP15);
	arrayDesA.push(arrayDesA15);
	arrayEspV.push(arrayEspV15);
	arrayWater.push(arrayWater15);
	arrayTime.push(arrayTime15);
	arrayDif.push(arrayDif15);
	arrayDif_image.push(arrayDif_image15);

	var arrayDistance16="5000 METRES";
	var arraySign16="Joan Miró sports circuit";
	var arrayTerrain16="ASPHALT, SAND AND GRASS";
	var arrayDay16="ALL DAY (while there’s light)";
	var arrayDesP16="80 METRES";
	var arrayDesA16="100 METRES";
	var arrayEspV16="images/niveles/nivelbosque3.png";
	var arrayWater16="images/niveles/nivelfuentes2.png";
	var arrayTime16="40 MINUTES";
	var arrayDif16="MEDIUM-HIGH";
	var arrayDif_image16="images/niveles/niveldificultad7.png";
	arrayDistance.push(arrayDistance16);
	arraySign.push(arraySign16);
	arrayTerrain.push(arrayTerrain16);
	arrayDay.push(arrayDay16);
	arrayDesP.push(arrayDesP16);
	arrayDesA.push(arrayDesA16);
	arrayEspV.push(arrayEspV16);
	arrayWater.push(arrayWater16);
	arrayTime.push(arrayTime16);
	arrayDif.push(arrayDif16);
	arrayDif_image.push(arrayDif_image16);


	var perfil="Profile";
	var infoProfile="Info";


	var arrayDistance17="8000 METRES";
	var arraySign17="ROUTE 100% arraySIGNPOSTED";
	var arrayTerrain17="EARTH";
	var arrayDay17="MORNINGS AND AFTERNOONS";
	var arrayDesP17="14 METRES";
	var arrayDesA17="43 METRES";
	var arrayEspV17="images/niveles/nivelbosque4.png";
	var arrayWater17="images/niveles/nivelfuentes3.png";
	var arrayTime17="45 MINUTES";
	var arrayDif17="LOW";
	var arrayDif_image17="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance17);
	arraySign.push(arraySign17);
	arrayTerrain.push(arrayTerrain17);
	arrayDay.push(arrayDay17);
	arrayDesP.push(arrayDesP17);
	arrayDesA.push(arrayDesA17);
	arrayEspV.push(arrayEspV17);
	arrayWater.push(arrayWater17);
	arrayTime.push(arrayTime17);
	arrayDif.push(arrayDif17);
	arrayDif_image.push(arrayDif_image17);

	var arrayDistance18="3500 METRES";
	var arraySign18="NO";
	var arrayTerrain18="SAND AND ASPHALT";
	var arrayDay18="ALL DAY (while there’s daylight)";
	var arrayDesP18="110 METRES";
	var arrayDesA18="117 METRES";
	var arrayEspV18="images/niveles/nivelbosque3.png";
	var arrayWater18="images/niveles/nivelfuentes3.png";
	var arrayTime18="30 MINUTES";
	var arrayDif18="HIGH";
	var arrayDif_image18="images/niveles/niveldificultad8.png";
	arrayDistance.push(arrayDistance18);
	arraySign.push(arraySign18);
	arrayTerrain.push(arrayTerrain18);
	arrayDay.push(arrayDay18);
	arrayDesP.push(arrayDesP18);
	arrayDesA.push(arrayDesA18);
	arrayEspV.push(arrayEspV18);
	arrayWater.push(arrayWater18);
	arrayTime.push(arrayTime18);
	arrayDif.push(arrayDif18);
	arrayDif_image.push(arrayDif_image18);

	var arrayDistance19="7000 METRES";
	var arraySign19="NO";
	var arrayTerrain19="EARTH";
	var arrayDay19="MORNINGS";
	var arrayDesP19="0 METRES";
	var arrayDesA19="181 METRES";
	var arrayEspV19="images/niveles/nivelbosque4.png";
	var arrayWater19="images/niveles/nivelfuentes2.png";
	var arrayTime19="50 MINUTES";
	var arrayDif19="MEDIUM-HIGH";
	var arrayDif_image19="images/niveles/niveldificultad7.png";
	arrayDistance.push(arrayDistance19);
	arraySign.push(arraySign19);
	arrayTerrain.push(arrayTerrain19);
	arrayDay.push(arrayDay19);
	arrayDesP.push(arrayDesP19);
	arrayDesA.push(arrayDesA19);
	arrayEspV.push(arrayEspV19);
	arrayWater.push(arrayWater19);
	arrayTime.push(arrayTime19);
	arrayDif.push(arrayDif19);
	arrayDif_image.push(arrayDif_image19);

	var arrayDistance20="3500 METRES";
	var arraySign20="NO";
	var arrayTerrain20="ASPHALT";
	var arrayDay20="MORNINGS";
	var arrayDesP20="88.7 METRES";
	var arrayDesA20="88.7 METRES";
	var arrayEspV20="images/niveles/nivelbosque1.png";
	var arrayWater20="images/niveles/nivelfuentes1.png";
	var arrayTime20="40 MINUTES";
	var arrayDif20="MEDIUM";
	var arrayDif_image20="images/niveles/niveldificultad.png";
	arrayDistance.push(arrayDistance20);
	arraySign.push(arraySign20);
	arrayTerrain.push(arrayTerrain20);
	arrayDay.push(arrayDay20);
	arrayDesP.push(arrayDesP20);
	arrayDesA.push(arrayDesA20);
	arrayEspV.push(arrayEspV20);
	arrayWater.push(arrayWater20);
	arrayTime.push(arrayTime20);
	arrayDif.push(arrayDif20);
	arrayDif_image.push(arrayDif_image20);


	var arrayDistance21="9000 METRES";
	var arraySign21="NO";
	var arrayTerrain21="GRASS AND PAVING";
	var arrayDay21="MORNINGS AND AFTERNOONS (while there’s daylight)";
	var arrayDesP21="20 METRES";
	var arrayDesA21="20 METRES";
	var arrayEspV21="images/niveles/nivelbosque4.png";
	var arrayWater21="images/niveles/nivelfuentes1.png";
	var arrayTime21="50 MINUTES";
	var arrayDif21="LOW";
	var arrayDif_image21="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance21);
	arraySign.push(arraySign21);
	arrayTerrain.push(arrayTerrain21);
	arrayDay.push(arrayDay21);
	arrayDesP.push(arrayDesP21);
	arrayDesA.push(arrayDesA21);
	arrayEspV.push(arrayEspV21);
	arrayWater.push(arrayWater21);
	arrayTime.push(arrayTime21);
	arrayDif.push(arrayDif21);
	arrayDif_image.push(arrayDif_image21);

	var arrayDistance22="6500 METRES";
	var arraySign22="NO";
	var arrayTerrain22="ASPHALT";
	var arrayDay22="MORNINGS AND AFTERNOONS";
	var arrayDesP22="-2 METRES";
	var arrayDesA22="20 METRES";
	var arrayEspV22="images/niveles/nivelbosque1.png";
	var arrayWater22="images/niveles/nivelfuentes1.png";
	var arrayTime22="40 MINUTES";
	var arrayDif22="LOW";
	var arrayDif_image22="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance22);
	arraySign.push(arraySign22);
	arrayTerrain.push(arrayTerrain22);
	arrayDay.push(arrayDay22);
	arrayDesP.push(arrayDesP22);
	arrayDesA.push(arrayDesA22);
	arrayEspV.push(arrayEspV22);
	arrayWater.push(arrayWater22);
	arrayTime.push(arrayTime22);
	arrayDif.push(arrayDif22);
	arrayDif_image.push(arrayDif_image22);

	var arrayDistance23="5200 METRES";
	var arraySign23="NO";
	var arrayTerrain23="ASPHALT";
	var arrayDay23="NIGHT";
	var arrayDesP23="16 METRES";
	var arrayDesA23="29 METRES";
	var arrayEspV23="images/niveles/nivelbosque1.png";
	var arrayWater23="images/niveles/nivelfuentes2.png";
	var arrayTime23="30 MINUTES";
	var arrayDif23="LOW";
	var arrayDif_image23="images/niveles/niveldificultad2.png";
	arrayDistance.push(arrayDistance23);
	arraySign.push(arraySign23);
	arrayTerrain.push(arrayTerrain23);
	arrayDay.push(arrayDay23);
	arrayDesP.push(arrayDesP23);
	arrayDesA.push(arrayDesA23);
	arrayEspV.push(arrayEspV23);
	arrayWater.push(arrayWater23);
	arrayTime.push(arrayTime23);
	arrayDif.push(arrayDif23);
	arrayDif_image.push(arrayDif_image23);

	var arrayCursa = [];

	var arrayCursa0="The Sant Antoni neighbourhood race";
	var arrayCursa1="Half marathon";
	var arrayCursa2="Marathon";
	var arrayCursa3="Firemen’s race";
	var arrayCursa4="The Corte Inglés race";
	var arrayCursa5="The Mercè race";
	var arrayCursa6="Friendship race";
	var arrayCursa7="Women’s Race";
	var arrayCursa8="Jean Bouin";
	var arrayCursa9="Cursa dels Nassos";
	arrayCursa.push(arrayCursa0);
	arrayCursa.push(arrayCursa1);
	arrayCursa.push(arrayCursa2);
	arrayCursa.push(arrayCursa3);
	arrayCursa.push(arrayCursa4);
	arrayCursa.push(arrayCursa5);
	arrayCursa.push(arrayCursa6);
	arrayCursa.push(arrayCursa7);
	arrayCursa.push(arrayCursa8);
	arrayCursa.push(arrayCursa9);

	var arrayRoute = [];
	var routesbot = [];

	var rutasdistritos="ROUTES BY DISTRICTS";
	var route1="Past, present and future of the Olympic Mountain";
	var routebot1="Plaça d'Espanya – Olympic Stadium – Montjuïc Castle";
	var route2="San Andreu full steam ahead";
	var routebot2="Plaça d'Orfila -  La Maquinista - Ronda Litoral - Plaça d'Orfila";
	var route3="Les Corts, red and blue (blaugrana) and green";
	var routebot3="Parc Maternitat - Parc Castell de l'Oreneta - Parc de Cervantes";
	var route4="Fly over the ring road";
	var routebot4="Horta Cycle Track – Parc del Castell de l’Oreneta – Parc de Cervantes";
	var route5="The athletes' Fòrum";
	var routebot5="Rambla de Prim - Fòrum - Plaça de les Glòries";
	var route6="Winding up to the Cycle Track";
	var routebot6="El Congrés neighbourhood - Turó de la Peira - Horta Cycle Track";
	var route7="Running is Modernista";
	var routebot7="Sagrada Família - Hospital de Sant Pau - Parc del Guinardó";
	var route8="Going up to the Font del Gat";
	var routebot8="Parc de les Cascades - Moll de la Fusta - Miramar - Font del Gat";
	var route9="A first category climb";
	var routebot9="Via Favència - Torre Baró - Via Júlia - Parc de la Guineueta";
	var route10="The three hills";
	var routebot10="Turó del Putget - Parc Güell - Turó del Carmel - Parc del Guinardó";
	var rutastematicas="THEMED ROUTES";
	var route11="Parks and gardens";
	var routebot11="Diagonal Mar - Carles I - Ciutadella";
	var route12="Cold days";
	var routebot12="Hotel Vela - Nova Icària -  Fòrum";
	var route13="City block interiors";
	var routebot13="Palau Robert - Calàbria - Plaça de la Universitat";
	var route14="Feast days";
	var routebot14="Plaça de Catalunya - Plaça de Sant Jaume - Estació de França";
	var route15="Beginners";
	var routebot15="Can Dragó - Plaça de les Glòries - Arc de Triomf";
	var route16="The athlete's Montjuïc";
	var routebot16="Parc de Joan Miró - Joan Serrahima stadium- Mirador del Migdia";
	var route17="The all-time classic: Carretera de les Aigües";
	var routebot17="Pla dels Maduixers - Vallvidrera - Sant Pere Màrtir";
	var route18="The old municipalities";
	var routebot18="Sarrià - Parc de Joan Raventós - Vallvidrera";
	var rutasrepte="ROUTES WITH A CHALLENGE";
	var route19="Hill running";
	var routebot19="Vallvidrera - La Budellera - Vallvidrera reservoir";
	var route20="From the shoreline to Sarrià";
	var routebot20="Jardins de les Tres Xemeneies- Entença - Sarrià";
	var route21="Going upriver";
	var routebot21="Bon Pastor - Besòs - Vallbona";
	var route22="Just one street";
	var routebot22="Plaça de les Glòries - Passeig de Gràcia - Plaça de Cerdà";
	var route23="Running by night";
	var routebot23="Travessera de les Corts  - Travessera de Gràcia - Plaça d'en Joanic";
	var rutaLliure="FREE ROUTE";
	var route24="Barcelona on demand";
	var rutaLliureText="With this option you can make your own route.";

	arrayRoute.push(route1);
	arrayRoute.push(route1);
	arrayRoute.push(route2);
	arrayRoute.push(route3);
	arrayRoute.push(route4);
	arrayRoute.push(route5);
	arrayRoute.push(route6);
	arrayRoute.push(route7);
	arrayRoute.push(route8);
	arrayRoute.push(route9);
	arrayRoute.push(route10);
	arrayRoute.push(route11);
	arrayRoute.push(route12);
	arrayRoute.push(route13);
	arrayRoute.push(route14);
	arrayRoute.push(route15);
	arrayRoute.push(route16);
	arrayRoute.push(route17);
	arrayRoute.push(route18);
	arrayRoute.push(route19);
	arrayRoute.push(route20);
	arrayRoute.push(route21);
	arrayRoute.push(route22);
	arrayRoute.push(route23);

	routesbot.push(routebot1);
	routesbot.push(routebot1);
	routesbot.push(routebot2);
	routesbot.push(routebot3);
	routesbot.push(routebot4);
	routesbot.push(routebot5);
	routesbot.push(routebot6);
	routesbot.push(routebot7);
	routesbot.push(routebot8);
	routesbot.push(routebot9);
	routesbot.push(routebot10);
	routesbot.push(routebot11);
	routesbot.push(routebot12);
	routesbot.push(routebot13);
	routesbot.push(routebot14);
	routesbot.push(routebot15);
	routesbot.push(routebot16);
	routesbot.push(routebot17);
	routesbot.push(routebot18);
	routesbot.push(routebot19);
	routesbot.push(routebot20);
	routesbot.push(routebot21);
	routesbot.push(routebot22);
	routesbot.push(routebot23);